*&---------------------------------------------------------------------*
*& Exercicio 047
*&---------------------------------------------------------------------*

REPORT ZPR_EXERC_FB_047.


*Write an executable program that reads the current system time and write the time in 6
*different zones (3 of them should be compulsorily Greenwich, Delhi and Brasilia).

  DATA V_TIMEZONE1 TYPE TZNZONE VALUE 'GMTUK'. " Greenwich
  DATA V_TIMEZONE2 TYPE TZNZONE VALUE 'INDIA'. " Delhi
  DATA V_TIMEZONE3 TYPE TZNZONE VALUE 'BRAZIL'. " Brasilia
  DATA V_TIMEZONE4 TYPE TZNZONE VALUE 'CST'.
  DATA V_TIMEZONE5 TYPE TZNZONE VALUE 'ISRAEL'.
  DATA V_TIMEZONE6 TYPE TZNZONE VALUE 'RUS06'.

  DATA V_TIMESTAMP TYPE TZONREF-TSTAMPS.
  DATA V_TIMESTAMP_STRING TYPE STRING.

START-OF-SELECTION.

  CONCATENATE SY-DATUM SY-UZEIT INTO V_TIMESTAMP_STRING.
  V_TIMESTAMP = V_TIMESTAMP_STRING.

  WRITE / 'Exercicio 047'.
  WRITE V_TIMESTAMP TIME ZONE V_TIMEZONE1. NEW-LINE.
  WRITE V_TIMESTAMP TIME ZONE V_TIMEZONE2. NEW-LINE.
  WRITE V_TIMESTAMP TIME ZONE V_TIMEZONE3. NEW-LINE.
  WRITE V_TIMESTAMP TIME ZONE V_TIMEZONE4. NEW-LINE.
  WRITE V_TIMESTAMP TIME ZONE V_TIMEZONE5. NEW-LINE.
  WRITE V_TIMESTAMP TIME ZONE V_TIMEZONE6. NEW-LINE.