*&---------------------------------------------------------------------*
*& Exercicio 072
*&---------------------------------------------------------------------*

REPORT ZPR_EXERC_FB_072.

*Have a routine that receives an internal table (with at least three fields) and another internal
*table with the name of the columns to be ordered and order accordingly

TYPES: BEGIN OF TY_EX072,
         ID    TYPE N LENGTH 8,
         NOME  TYPE C LENGTH 23,
         IDADE TYPE I,
       END OF TY_EX072,

       BEGIN OF TY_EX072_B,
         COLUNA TYPE C LENGTH 20,
       END OF TY_EX072_B.



TYPES TY_table7 TYPE STANDARD TABLE OF TY_EX072.
TYPES TY_COLUNAS TYPE STANDARD TABLE OF TY_EX072_B.

DATA: IT_REGISTRO4 TYPE  TY_table7,
      IT_COLUNA    TYPE TY_COLUNAS,
      WA_REGISTRO4 TYPE TY_EX072,
      WA_COLUNA    TYPE TY_EX072_B.

START-OF-SELECTION.



  WA_REGISTRO4-ID = 4.
  WA_REGISTRO4-NOME = 'Manuella'.
  WA_REGISTRO4-IDADE = 07.
  APPEND WA_REGISTRO4 TO IT_REGISTRO4.

  WA_REGISTRO4-ID = 1.
  WA_REGISTRO4-NOME = 'Felype'.
  WA_REGISTRO4-IDADE = 22.
  APPEND WA_REGISTRO4 TO IT_REGISTRO4.


  WA_REGISTRO4-ID = 3.
  WA_REGISTRO4-NOME = 'Vitor'.
  WA_REGISTRO4-IDADE = 16.
  APPEND WA_REGISTRO4 TO IT_REGISTRO4.


  WA_REGISTRO4-ID = 2.
  WA_REGISTRO4-NOME = 'Gabriel'.
  WA_REGISTRO4-IDADE = 19.
  APPEND WA_REGISTRO4 TO IT_REGISTRO4.

  WA_REGISTRO4-ID = 6.
  WA_REGISTRO4-NOME = 'Laudenir'.
  WA_REGISTRO4-IDADE = 50.
  APPEND WA_REGISTRO4 TO IT_REGISTRO4.

  WA_REGISTRO4-ID = 5.
  WA_REGISTRO4-NOME = 'Lucilene'.
  WA_REGISTRO4-IDADE = 46.
  APPEND WA_REGISTRO4 TO IT_REGISTRO4.

  WA_COLUNA-COLUNA = 'IDADE'.
  APPEND WA_COLUNA  TO it_COLUNA.

  WA_COLUNA-COLUNA = 'ID'.
  APPEND WA_COLUNA  TO it_COLUNA.

  WA_COLUNA-COLUNA = 'NOME'.
  APPEND WA_COLUNA  TO it_COLUNA.

  CLEAR: WA_REGISTRO4, WA_COLUNA.

  PERFORM ZF_EX072 USING it_COLUNA CHANGING IT_REGISTRO4.



FORM ZF_EX072 USING NAMECOLUM TYPE TY_COLUNAS CHANGING IT_TESTE2 TYPE  TY_table7.

  DATA LV_NOME_COLUN TYPE C LENGTH 20.

  LOOP AT NAMECOLUM  INTO WA_COLUNA .

    LV_NOME_COLUN = WA_COLUNA.
    SORT IT_TESTE2 BY (LV_NOME_COLUN) ASCENDING.
    PERFORM ZF_APRESENTA CHANGING IT_TESTE2.

  ENDLOOP.




ENDFORM.


FORM ZF_APRESENTA CHANGING IT_TESTE2 TYPE TY_table7.

  CLEAR: WA_REGISTRO4.
   WRITE: / 'Exercício 72'.
   LOOP AT IT_TESTE2 INTO WA_REGISTRO4.

    WRITE: / 'Registro: ', WA_REGISTRO4-ID, WA_REGISTRO4-NOME, WA_REGISTRO4-IDADE.

  ENDLOOP.

  ENDFORM.