*&---------------------------------------------------------------------*
*&  Exercicio 88
*&---------------------------------------------------------------------*

REPORT ZPR_EXERC_FB_088.


*Create a tabbed block with 3 tabs. Each of them should have a different content.

  SELECTION-SCREEN: BEGIN OF BLOCK BTESTE1 WITH FRAME.

    PARAMETERS CB_TESTE AS CHECKBOX.

  SELECTION-SCREEN: END OF BLOCK BTESTE1.


  SELECTION-SCREEN: BEGIN OF BLOCK BTESTE2 WITH FRAME.

    PARAMETERS P_TESTE TYPE STRING.

  SELECTION-SCREEN: END OF BLOCK BTESTE2.


  SELECTION-SCREEN: BEGIN OF BLOCK BTESTE3 WITH FRAME.

    PARAMETERS RB_TESTE RADIOBUTTON GROUP GTE3.
    PARAMETERS RB_TEST2 RADIOBUTTON GROUP GTE3.

  SELECTION-SCREEN: END OF BLOCK BTESTE3.


  SELECTION-SCREEN BEGIN OF SCREEN 1 AS SUBSCREEN.
    PARAMETER P_1 TYPE STRING.
  SELECTION-SCREEN END OF SCREEN 1.
  SELECTION-SCREEN BEGIN OF SCREEN 2 AS SUBSCREEN.
    PARAMETER P_2 TYPE D.
  SELECTION-SCREEN END OF SCREEN 2.
  SELECTION-SCREEN BEGIN OF SCREEN 3 AS SUBSCREEN.
    PARAMETER P_3 TYPE T.
  SELECTION-SCREEN END OF SCREEN 3.
  SELECTION-SCREEN BEGIN OF TABBED BLOCK TB FOR 10 LINES.
    SELECTION-SCREEN TAB (10) TAB1 USER-COMMAND TAB1_PRESSED DEFAULT SCREEN 1.
    SELECTION-SCREEN TAB (10) TAB2 USER-COMMAND TAB2_PRESSED DEFAULT SCREEN 2.
    SELECTION-SCREEN TAB (10) TAB3 USER-COMMAND TAB3_PRESSED DEFAULT SCREEN 3.
  SELECTION-SCREEN END OF BLOCK TB.

INITIALIZATION.
  TAB1 = 'String'.
  TAB2 = 'Date'.
  TAB3 = 'Time'.